apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-workspace.deploymentName" . }}
  namespace: {{ .Values.deploymentNamespace | default "default" }}
  labels:
    app: {{ include "test-workspace.deploymentName" . }}
spec:
  replicas: {{ .Values.deploymentNumReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.deploymentName }}
    spec:
      containers:
        - name: {{ include "test-workspace.deploymentName" . }}
          image: {{ .Values.deploymentImage }}
          command: ["sleep", "infinity"]
          resources:
            requests:
              cpu: {{ .Values.cpuCores }}
              memory: {{ .Values.memoryGb }}Gi
              nvidia.com/gpu: {{ .Values.gpuCount }}
              ephemeral-storage: {{ .Values.ephemeralStorageGb }}Gi
            limits:
              cpu: {{ .Values.cpuCores }}
              memory: {{ .Values.memoryGb }}Gi
              nvidia.com/gpu: {{ .Values.gpuCount }}
              ephemeral-storage: {{ .Values.ephemeralStorageGb }}Gi
          ports:
            - containerPort: 8080
              name: http