apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-workspace.deploymentName" . }}
  namespace: {{ .Values.global.deploymentNamespace | default "default" }}
  labels:
    app: {{ include "test-workspace.deploymentName" . }}
spec:
  replicas: {{ .Values.deploymentNumReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.deploymentName }}
        workspace.exalsius.ai/database-id: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "test-workspace.deploymentName" . }}
          image: {{ .Values.deploymentImage }}
          command: ["sleep", "infinity"]
          resources:
            requests:
              ephemeral-storage: 5Gi
              cpu: {{ .Values.resources.cpuCores }}
              memory: {{ .Values.resources.memoryGb }}Gi
              nvidia.com/gpu: {{ .Values.resources.gpuCount }}
            limits:
              ephemeral-storage: 10Gi
              cpu: {{ .Values.resources.cpuCores }}
              memory: {{ .Values.resources.memoryGb }}Gi
              nvidia.com/gpu: {{ .Values.resources.gpuCount }}
          ports:
            - containerPort: 8080
              name: http