apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vscode-devcontainer.deploymentName" . }}
  namespace: {{ .Values.global.deploymentNamespace }}
  labels:
    app: {{ include "vscode-devcontainer.deploymentName" . }}
spec:
  replicas: {{ .Values.deploymentNumReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.deploymentName }}-code
  template:
    metadata:
      labels:
        app: {{ .Values.global.deploymentName }}-code
        workspace.exalsius.ai/database-id: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 0
{{- if and .Values.resources.gpuCount (gt (int .Values.resources.gpuCount) 0) (eq (lower .Values.resources.gpuVendor) "nvidia") }}
      runtimeClassName: nvidia
{{- end }}
      containers:
        - name: devpod
          image: {{ include "vscode-devcontainer.image" . }}
          imagePullPolicy: Always
          ports:
            - containerPort: 22
              name: ssh
          env:
{{- if .Values.sshPassword }}
            - name: DEV_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vscode-devcontainer.secretName" . }}
                  key: SSH_PASSWORD
{{- end }}
{{- if .Values.sshPublicKey }}
            - name: DEV_SSH_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "vscode-devcontainer.secretName" . }}
                  key: SSH_PUBLIC_KEY
{{- end }}
          volumeMounts:
            - name: {{ include "vscode-devcontainer.storageVolumeName" . }}
              mountPath: /workspace
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              ephemeral-storage: 5Gi
              cpu: {{ .Values.resources.cpuCores }}
              memory: {{ .Values.resources.memoryGb }}Gi
{{- if and .Values.resources.gpuCount (gt (int .Values.resources.gpuCount) 0) }}
{{- if eq (lower .Values.resources.gpuVendor) "nvidia" }}
              nvidia.com/gpu: {{ .Values.resources.gpuCount }}
{{- else if eq (lower .Values.resources.gpuVendor) "amd" }}
              amd.com/gpu: {{ .Values.resources.gpuCount }}
{{- end }}
{{- end }}
            limits:
              ephemeral-storage: 10Gi
              cpu: {{ .Values.resources.cpuCores }}
              memory: {{ .Values.resources.memoryGb }}Gi
{{- if and .Values.resources.gpuCount (gt (int .Values.resources.gpuCount) 0) }}
{{- if eq (lower .Values.resources.gpuVendor) "nvidia" }}
              nvidia.com/gpu: {{ .Values.resources.gpuCount }}
{{- else if eq (lower .Values.resources.gpuVendor) "amd" }}
              amd.com/gpu: {{ .Values.resources.gpuCount }}
{{- end }}
{{- end }}
      volumes:
        - name: {{ include "vscode-devcontainer.storageVolumeName" . }}
          persistentVolumeClaim:
            claimName: {{ include "vscode-devcontainer.pvcName" . }}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.shmSizeGb }}Gi
