# Jupyter Notebook Helm Chart Values

# DO NOT CHANGE THIS PARAMETER
deploymentNumReplicas: 1

# Deployment configuration
deploymentName: "my-notebook"
deploymentNamespace: "default"
deploymentImage: "ghcr.io/exalsius/jupyter-notebook:latest-nvidia"

# Jupyter Notebook configuration
notebookPassword: "mysecurepassword"

# Ephemeral storage storage configuration
ephemeralStorageGb: 50

# Resource configuration (this maps to ResourcePool spec in API, but camelcase)
cpuCores: 16
memoryGb: 32
storageGb: 50
gpuCount: 1
