# Jupyter Notebook Helm Chart Values
deploymentImage: "ghcr.io/exalsius/jupyter-notebook:latest-nvidia"

# Jupyter Notebook configuration
notebookPassword: "mysecurepassword"

##################################################################
########## ONLY HERE FOR REFERENCE OR LOCAL TESTING ##############
########## Values are set automatically by exalsius ##############
##################################################################
global:
  deploymentName: "my-notebook"
  deploymentNamespace: "default"

resources:
  # Ephemeral storage configuration
  ephemeralStorageGb: 50
  cpuCores: 16
  memoryGb: 32
  storageGb: 50
  gpuCount: 1

deploymentNumReplicas: 1