# Jupyter Notebook Helm Chart Values
deploymentImage: "ghcr.io/exalsius/jupyter-notebook:latest-nvidia"

# Ephemeral storage configuration
ephemeralStorageGb: 50

# Jupyter Notebook configuration
notebookPassword: "mysecurepassword"

##################################################################
########## ONLY HERE FOR REFERENCE OR LOCAL TESTING ##############
########## Values are set automatically by exalsius ##############
##################################################################
global:
  deploymentName: "my-notebook"
  deploymentNamespace: "default"

resources:
  gpuCount: 1
  gpuVendor: "NVIDIA"
  gpuType: "L40"
  gpuMemory: 24
  cpuCores: 16
  memoryGb: 32
  storageGb: 50

deploymentNumReplicas: 1