# Test Workspace Helm Chart Values
deploymentImage: "ubuntu:22.04"

# Ephemeral storage configuration
ephemeralStorageGb: 10

##################################################################
########## ONLY HERE FOR REFERENCE OR LOCAL TESTING ##############
########## Values are set automatically by exalsius ##############
##################################################################
global:
  deploymentName: "test-workspace"
  deploymentNamespace: "default"

resources:
  gpuCount: 0
  gpuVendor: "NVIDIA"
  gpuType: "L40"
  gpuMemory: 24
  cpuCores: 1
  memoryGb: 2
  storageGb: 10

deploymentNumReplicas: 1