apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "marimo.deploymentName" . }}
  namespace: {{ .Values.global.deploymentNamespace | default "default" }}
  labels:
    app: {{ include "marimo.deploymentName" . }}
spec:
  replicas: {{ .Values.deploymentNumReplicas }}
  selector:
    matchLabels:
      app: {{ include "marimo.deploymentName" . }}
  template:
    metadata:
      labels:
        app: {{ include "marimo.deploymentName" . }}
        workspace.exalsius.ai/database-id: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 0
{{- if and .Values.resources.gpuCount (gt (int .Values.resources.gpuCount) 0) (eq (lower .Values.resources.gpuVendor) "nvidia") }}
      runtimeClassName: nvidia
{{- end }}
      containers:
        - name: {{ include "marimo.deploymentName" . }}
          image: {{ .Values.deploymentImage }}
          workingDir: /data
          env:
            - name: TOKEN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "marimo.secretName" . }}
                  key: TOKEN_PASSWORD
          command: ["sh", "-c"]
          args:
            - >
              marimo edit --token --token-password="${TOKEN_PASSWORD}"
              -p 8080 --host 0.0.0.0
          volumeMounts:
            - name: {{ include "marimo.storageVolumeName" . }}
              mountPath: /data
          resources:
            requests:
              ephemeral-storage: 5Gi
              cpu: {{ .Values.resources.cpuCores }}
              memory: {{ .Values.resources.memoryGb }}Gi
{{- if eq (lower .Values.resources.gpuVendor) "nvidia" }}
              nvidia.com/gpu: {{ .Values.resources.gpuCount }}
{{- else if eq (lower .Values.resources.gpuVendor) "amd" }}
              amd.com/gpu: {{ .Values.resources.gpuCount }}
{{- end }}
            limits:
              ephemeral-storage: 10Gi
              cpu: {{ .Values.resources.cpuCores }}
              memory: {{ .Values.resources.memoryGb }}Gi
{{- if eq (lower .Values.resources.gpuVendor) "nvidia" }}
              nvidia.com/gpu: {{ .Values.resources.gpuCount }}
{{- else if eq (lower .Values.resources.gpuVendor) "amd" }}
              amd.com/gpu: {{ .Values.resources.gpuCount }}
{{- end }}
          ports:
            - containerPort: 8080
              name: marimo
      volumes:
        - name: {{ include "marimo.storageVolumeName" . }}
          persistentVolumeClaim:
            claimName: {{ include "marimo.pvcName" . }}