apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "performance-profiling.configmapName" . }}
  namespace: {{ .Values.global.deploymentNamespace }}
data:
  profiling_config.json: |
{{ .Files.Get "files/profiling_config.json" | indent 4 }}