# Marimo Helm Chart Values
deploymentImage: "ghcr.io/exalsius/marimo:latest-nvidia"

# Ephemeral storage storage configuration
ephemeralStorageGb: 50

# Marimo configuration
tokenPassword: "mysecurepassword"

##################################################################
########## ONLY HERE FOR REFERENCE OR LOCAL TESTING ##############
########## Values are set automatically by exalsius ##############
##################################################################
global:
  deploymentName: "my-marimo"
  deploymentNamespace: "default"

resources:
  gpuCount: 1
  gpuVendor: "NVIDIA"
  gpuType: "L40"
  gpuMemory: 24
  cpuCores: 16
  memoryGb: 32
  storageGb: 50  

deploymentNumReplicas: 1