# Marimo Helm Chart Values
deploymentImage: "ghcr.io/exalsius/marimo:latest-nvidia"

# Marimo configuration
tokenPassword: "mysecurepassword"

##################################################################
########## ONLY HERE FOR REFERENCE OR LOCAL TESTING ##############
########## Values are set automatically by exalsius ##############
##################################################################
global:
  deploymentName: "my-marimo"
  deploymentNamespace: "default"

resources:
  # Ephemeral storage storage configuration
  ephemeralStorageGb: 50
  # Resource configuration
  cpuCores: 16
  memoryGb: 32
  storageGb: 50
  # GPU vendor configuration - valid values: "NVIDIA" or "AMD"
  gpuVendor: "NVIDIA"
  gpuCount: 1

deploymentNumReplicas: 1