istiod:
  meshConfig:
    defaultConfig:
      proxyMetadata:
        # Necessary for GAIE to work
        ENABLE_GATEWAY_API_INFERENCE_EXTENSION: "true"
  pilot:
    env:
      # Necessary for GAIE to work
      ENABLE_GATEWAY_API_INFERENCE_EXTENSION: "true"
