custom-grafana-ingress:
  enabled: false
  ingressName: grafana-vm-ingress
  certManagerIssuer: letsencrypt
  annotations: {}
  ingressClassName: nginx
  # Requires customization for your environment
  host: grafana.kcm0.example.net
  certManagerSecretName: custom-grafana-ingress-tls
  serviceName: grafana-vm-service
  servicePort: 3000