{{- $remote := index .Values "remote-ingress" }}
{{- if $remote.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $remote.ingressName | quote }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ $remote.certManagerIssuer | quote }}
    {{- toYaml $remote.annotations | nindent 4 }}
spec:
  ingressClassName: {{ $remote.ingressClassName | quote }}
  tls:
    - hosts:
        - {{ $remote.host | quote }}
      secretName: {{ $remote.certManagerSecretName | quote }}
  rules:
    - host: {{ $remote.host | quote }}
      http:
        paths:
          - path: {{ $remote.path | quote }}
            pathType: {{ $remote.pathType | quote }}
            backend:
              service:
                name: {{ $remote.serviceName | quote }}
                port:
                  number: {{ $remote.servicePort | int }}
{{- end }}